In [10]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print("a:", a)
print("b:\n", b)



a: [1 2 3]
b:
 [[1 2 3]
 [4 5 6]]


In [11]:
import numpy as np

a = np.array([1, 2, 3])

print("Shape:", a.shape)
print("Dimensions:", a.ndim)
print("Size:", a.size)
print("Data type:", a.dtype)



Shape: (3,)
Dimensions: 1
Size: 3
Data type: int64


In [5]:
print(np.zeros((3,3)))
print(np.ones((2,4)))
print(np.full((2,2), 7))
print(np.eye(4))               # identity matrix)
print(np.arange(0, 10, 2))
print(np.linspace(1, 5, 10))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0 2 4 6 8]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [7]:
arr = np.array([10,20,30,40,50])

print(arr[0])          # 10)
print(arr[1:4])        # [20 30 40])
print(arr[::-1] )




10
[20 30 40]
[50 40 30 20 10]


In [18]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(m[0,1])
print(m[1, :2])
print(m[:, :2])
print(m[:,2])


2
[4 5]
[[1 2]
 [4 5]
 [7 8]]
[3 6 9]


In [ ]:
arr = np.array([1,4,7,2,8,3])

arr[arr > 4]     # [7 8]
arr[arr % 2 == 0] # even numbers


In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("a + b:", a + b)
print("a * b:", a * b)
print("Dot product:", a @ b)
print("np.dot:", np.dot(a, b))


a + b: [5 7 9]
a * b: [ 4 10 18]
Dot product: 32
np.dot: 32


In [13]:
arr = np.array([1, 2, 3, 4, 5])

print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())
print("Std:", arr.std())

Sum: 15
Mean: 3.0
Max: 5
Min: 1
Std: 1.4142135623730951


In [14]:

arr = np.array([1,2,3])
m = np.ones((3,3))

print("arr + 10:", arr + 10)
print("m + arr:\n", m + arr)

arr + 10: [11 12 13]
m + arr:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [15]:
a = np.arange(12)
print("Original:", a)
print("Reshaped (3,4):\n", a.reshape(3,4))
print("Reshaped (-1,2):\n", a.reshape(-1,2))

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped (-1,2):
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [19]:
x = np.array([1,2,3])
m = np.ones((3,3))

print(m + x)
print(x + 10)


[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[11 12 13]


In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Vertical stack:\n", np.vstack([a,b]))
print("Horizontal stack:", np.hstack([a,b]))


Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack: [1 2 3 4 5 6]


In [29]:
a = np.arange(31)
print(a)
print(a[a%5==0])
print(a[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[ 0  5 10 15 20 25 30]
[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7
  6  5  4  3  2  1  0]


In [43]:
a = np.arange(16)
print("a.size =", a.size) 
a = a.reshape(4,4)
print(a)
print(a[1:3,1:3])

a.size = 16
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5  6]
 [ 9 10]]


In [50]:
a=np.ones((3,3))
b=[10,20,30]
print(a+b)
print(np.vstack([a,b]))

[[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [10. 20. 30.]]


In [57]:
a = np.arange(50)
a = a.reshape(5,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [59]:
a = [1,2,3]
b = [4,5,6]
print(np.vstack([a,b]))
print(np.hstack([a,b]))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
